project:
  type: book
  output-dir: docs
  post-render:
    - "rm -rf images"
    - "rm -rf srcqmd/images"

book:
  title: "Minimum(ish) Working Example of Quarto with Arabic RTL text in an LTR document"
  author: "The Authors"
  date: "11/16/2024"
  chapters:
    - index.qmd
    - srcqmd/intro.qmd
    - srcqmd/arabic_support.qmd
    - srcqmd/transliteration.qmd
    - srcqmd/figures.qmd
    - srcqmd/summary.qmd
    - srcqmd/references.qmd
  downloads: [pdf]

#keep-md: true
filters:
  - arabic-support

bibliography: srcqmd/references.bib

format:
  html:
    mainfont: "Charis SIL"
    mainfontoptions: Numbers=OldStyle
    sansfont: "Charis SIL"
    monofont: "DejaVu Sans Mono" # set size in CSS using class "sourceCode"
    #fontsize: 10pt
    theme: cosmo
    css: srchtml/styles.css
    include-before-body: srchtml/watermark.html
  pdf:
    #keep-tex: true
    documentclass: scrreprt # no roman numeral pagination but chapter page can be left or right
    #documentclass: scrbook # new chapter page only on right but adds \frontmatter command for roman numeral pagination
    toc: true
    geometry:
      # A4 2 pages per sheet draft
      #- paper=a5paper               # a5: 148.5 by 210mm
      - paperwidth=170mm
      - paperheight=244mm
      #- paperwidth=156mm
      #- paperheight=234mm
      #- paperwidth=6in
      #- paperheight=9in
      - bindingoffset=6mm
      - textwidth=114.8mm           # = (170 - 6)*0.7
      - textheight=170.8mm          # = 244 * 0.7
      - twoside
    number-sections: true
    colorlinks: true
    mainfont: "Charis SIL"
    mainfontoptions: Numbers=OldStyle
    sansfont: "Charis SIL"
    monofont: "DejaVu Sans Mono"
    monofontoptions: "Scale=0.7"
    fontsize: 10pt
    pdf-engine: xelatex
    include-in-header:
      - file: srctex/include_in_header.tex
    include-before-body:
      - file: srctex/before_body.tex
    template-partials:
      - srctex/before-title.tex

tikzarabic:
  cache: true
  format: svg
  embed_mode: link
  engine: lualatex
  scale: 1.28
  template_html: srctex/tikz-template-html.tex
  template_pdf: srctex/tikz-template-pdf.tex
  libgs: /usr/local/Cellar/ghostscript/10.04.0/lib/libgs.dylib

