---
title: "Arabic-support Example"
keep-md: true
filters:
  - arabic-support
format:
  html:
    mainfont: "Charis SIL"
    #sansfont: "DejaVu Sans"
  pdf:
    keep-tex: true
    toc: true
    number-sections: true
    colorlinks: true
    mainfont: "Charis SIL"
    #sansfont: "DejaVu Sans"
    pdf-engine: xelatex
    documentclass: book
    # babelfont for Arabic font needs to be in the `template-partial`
    # `before-title.tex`. If I put it in the `include-in-header` option, then it
    # gets put before `\usepackage{babel}` and doesn't work.
    include-in-header:
      - file: srctex/include_in_header.tex
    include-before-body:
      - file: srctex/before_body.tex
    template-partials:
      - srctex/before-title.tex
---

# Heading with inline [عربي]{.ar}

This is some inline Arabic text [هَـٰذَا كَلَامٌ عَرَبِيٌّ.]{.ar}. This is its transliteration: [hApA kalAmun earabiyyun.]{.trn}. This is some Romanized Arabic text: [#eumar]{.trn2}, [E#usAmah]{.trn2}.

This is an Arabic div:

::: {.otherlanguage data-latex="{arabic}" lang="ar"}
هذا كلام عربي طويل. أريد أن أكتب حتى يبلغ الكلام سطرين. أستعمل برنامج قواطرو لإنتاج الملف الخارجي. هو برنامج جيد قد خلف البرنامج بكداؤن الذي كنت أستعمله من قبل.
:::

This is some English text after it.

## Some section

\lipsum[1-3]

### Some subection

\lipsum[4-9]

# A chapter

This is some inline Arabic text [هَـٰذَا كَلَامٌ عَرَبِيٌّ.]{.ar}. This is its transliteration: [hApA kalAmun earabiyyun.]{.trn}. This is some Romanized Arabic text: [#eumar]{.trn2}, [E#usAmah]{.trn2}.

This is an Arabic div:

::: {.otherlanguage data-latex="{arabic}" lang="ar"}
هذا كلام عربي طويل. أريد أن أكتب حتى يبلغ الكلام سطرين. أستعمل برنامج قواطرو لإنتاج الملف الخارجي. هو برنامج جيد قد خلف البرنامج بكداؤن الذي كنت أستعمله من قبل.
:::

This is some English text after it.

## Some section

\lipsum[1-5]

### Some subection

\lipsum[2-10]

