# Preface {.unnumbered}

[بسم الله الرحمن الرحيم]{.aralt}

[Quarto](https://quarto.org/docs/books) is a document publishing software. 
With it, you can write your document in [Pandoc flavored markdown](https://pandoc.org/MANUAL.html#pandocs-markdown).
Quarto will use Pandoc under the hood, and do a bunch of other fancy stuff, to output your markdown document in formats of your choice, like HTML for websites, and PDF (via [Latex](https://www.latex-project.org/)).

So far so good. But many of my documents are in English with Arabic content interspersed.
Arabic is written right-to-left (RTL) whereas English is written left-to-right (LTR).
The support of bidirectional (BiDi) text is a notoriously tricky problem.
The cursive property of the Arabic script (with joining letters) compounds the issue.

In this write-up, I will describe how to configure Quarto to solve some of these issues.

<!--2. This inline text: [العربية]{.ar} and this one: [سرب القطا]{.aralt} -->

The code for this book can be used as a template for RTL document projects. Along with BiDi, I'll also discuss other aspects like fonts, figures, etc. [إن شاء الله]{.aralt}.

The source code for this book can be found here: <https://github.com/adamiturabi/quarto-arabic-mwe>.

The rendered output is published here: <https://adamiturabi.github.io/quarto-arabic-mwe>.

A PDF version of this document can be downloaded if you click on the PDF icon next to the title at the top left of this page.

If you have any suggestions for improvements I'd love to know about them in the 
[discussions page](https://github.com/adamiturabi/quarto-arabic-mwe/discussions)
for this project.
