# Transliteration of Arabic 

## Romanization scheme

In my documents, I frequently need to transliterate and transcribe Arabic text in Latin characters.
There are various Romanization schemes in existence, using dots, macrons, etc.
The Romanization scheme I am using for a few of my projects is tabulated below:

| Arabic letter | Transliterated output | ASCII input |
|:--|:--|:--|
|[ء]{.ar}      | [E]{.trn}           | `E`|
|[ا]{.ar}      | [A]{.trn}           | `A`|
|[ب]{.ar}      | [b]{.trn}           | `b`|
|[ت]{.ar}      | [t]{.trn}           | `t`|
|[ث]{.ar}      | [v]{.trn}           | `v`|
|[ج]{.ar}      | [j]{.trn}           | `j`|
|[ح]{.ar}      | [H]{.trn}           | `H`|
|[خ]{.ar}      | [x]{.trn}           | `x`|
|[د]{.ar}      | [d]{.trn}           | `d`|
|[ذ]{.ar}      | [p]{.trn}           | `p`|
|[ر]{.ar}      | [r]{.trn}           | `r`|
|[ز]{.ar}      | [z]{.trn}           | `z`|
|[س]{.ar}      | [s]{.trn}           | `s`|
|[ش]{.ar}      | [c]{.trn}           | `c`|
|[ص]{.ar}      | [S]{.trn}           | `S`|
|[ض]{.ar}      | [D]{.trn}           | `D`|
|[ط]{.ar}      | [T]{.trn}           | `T`|
|[ظ]{.ar}      | [P]{.trn}           | `P`|
|[ع]{.ar}      | [e]{.trn}           | `e`|
|[غ]{.ar}      | [g]{.trn}           | `g`|
|[ف]{.ar}      | [f]{.trn}           | `f`|
|[ق]{.ar}      | [q]{.trn}           | `q`|
|[ك]{.ar}      | [k]{.trn}           | `k`|
|[ل]{.ar}      | [l]{.trn}           | `l`|
|[م]{.ar}      | [m]{.trn}           | `m`|
|[ن]{.ar}      | [n]{.trn}           | `n`|
|[ه]{.ar}      | [h]{.trn}           | `h`|
|[و]{.ar} (C/V)| [w]{.trn}/[U]{.trn} | `w`/`U`|
|[ي]{.ar} (C/V)| [y]{.trn}/[I]{.trn} | `y`/`I`|

As you can see, I use digraphs ([p]{.trn}, [g]{.trn}, etc.) for some letters.
This is because, for my current projects, I prefer readability over precision.

It is possible to input these special characters directly by modifying your keyboard layout or mapping, either at an operating system, or editor level.
Andreas Hallberg has described a technique for inputing them in the vim editor here:
<https://andreasmhallberg.github.io/ergonomic-arabic-transcription/>

For Quarto, I prefer to input the transliterated text as ASCII characters.
I have written a Lua filter [`transliteration-span.lua`](https://github.com/adamiturabi/quarto-arabic-mwe/blob/main/_extensions/arabic-support/transliteration-span.lua)
to handle rendering them correctly. 
The mapping of ASCII input to transliterated output is shown in the table above
and is encoded in the filter. 
So if I input:

```md
[pahabtu maphaban]{.trn}
```

It will be output as 
[pahabtu maphaban]{.trn}.

Note the dot character · is automatically inserted by the filter between the digraph [p]{.trn} and the following [h]{.trn} for helping in disambiguation.

With `{.trn}` the output is in italic (as above).
But sometimes I need to have non-italic output, as in the case of names. For that I use `{.trn2}`. For example:

```md
[#eAEicah]{.trn2} and [E#Adam]{.trn2} are studying 
the [#qurEAn]{.trn2} and [#HadIv]{.trn2}.
```

This is rendered as:

[#eAEicah]{.trn2} and [E#Adam]{.trn2} are studying the [#qurEAn]{.trn2} and [#HadIv]{.trn2}.

Note how the hash character `#` is used to control capitalization.

## Fonts

For the Latin font used in your main text, you will need to pick a font that supports the dots, macrons, breves, etc needed for transliteration. 
For my transliteration scheme, the font will also need to support `U+02be` for [E]{.trn} and `U+025b` for [e]{.trn}.
Not all Latin fonts support these extra characters.
In this document, I am using the 
[Charis SIL](https://software.sil.org/charis/download/)
font.

Other fonts I have experimented with, that have varied support for these characters, are:

+ [New Computer Modern](https://ctan.org/pkg/newcomputermodern?lang=en)
+ [DejaVu Serif](https://github.com/dejavu-fonts/dejavu-fonts/releases)
+ [Junicode](https://github.com/psb1558/Junicode-font/releases)
+ [Brill](https://brill.com/page/419386?language=en)
+ [Gentium Plus](https://software.sil.org/gentium/download/)
+ [STIX Two Text](https://github.com/stipub/stixfonts/releases)

## Test transliteration [Eabjd hwz HTy klmn sefS qrct vxp DPg AUI]{.trn}

Dummy text


